### ISSUE TITLE
Please clarify why bootstrapping requires a password

### ISSUE THREAD

**Issue by cfa** [melezhik/tomtit#1]
From the instructions in README.md,

> You need to bootstrap your system to start using tomtit, it's a one time operation,
> where you install Sparrow which is underlying tomtit runner.
>     
>     tom --bootstrap 

It'd be helpful to clarify that this (`sparrowdo --local_mode --bootstrap`) requires a password and explain why. I was surprised to see the prompt and cancelling bootstrapping as a result.

**Comment by melezhik** [comment]
Yeah, the bootstrap operation install sparrow client to your system. Sparrow gets installed as CPAN module, but it also install perl and other system packages ( perl-dev, ssl so on ) to ensure bootstrap on clean machine ... this requires sudo. If sudo is not an option for you, you just need to install Sparrow on your machine and that is it:

```
cpanm Sparrow 
```

HTH


PS. I might add clarification to the doc if you help me with that

**Comment by cfa** [comment]
Thanks—I'll go the `cpanm` route.

Regarding documentation, clarifying that this is all that `--bootstrap` is doing should be sufficient? Something like:

> You need to bootstrap your system to start using tomtit. This is a one time operation,
> where you install Sparrow which is underlying tomtit runner. For system-wide installation,
> run
>     
>     tom --bootstrap 
>
> or if you use `cpanm`, simply install `Sparrow` as follows
>
>     cpanm Sparrow 

might suffice?

**Comment by melezhik** [comment]
Yeah, the reason I "hide" it under `tomtit --boostrap` that I don't want a user get bothered with underlying Tomtit details ( Tomtit uses Sparrowdo which in turns uses Sparrow so on ), probably you're right if we have it here in upfront way, what do you think?

**Comment by cfa** [comment]
Understood.

How about an additional flag that wraps the `cpanm` call then?

> or if you'd prefer to install dependencies using `cpanm`,
>
>     tom --bootstrap-locally

**Comment by cfa** [comment]
(Wrapping `cpanm` also means that you can add dependencies in the future without having to update the bootstrap documentation.)

**Comment by melezhik** [comment]
Well, I like the idea, I'd only rephrase it like this:

```
tom # first tomtit run

Hmm, looks like you run tomtit for the first time, 
you need to install Sparrow which is underlying Tomtit runner, 
choose between two options:

1) local install - only require Perl and cpan/cpanm on your machine
2) system install - recommend  on fresh machines, requires sudo     
```
What do you think?

**Comment by cfa** [comment]
SGTM.

**Comment by cfa** [comment]
I think so, yeah.

As long as there's (i) support for `cpanm` and (ii) some context/explanation before the password prompt the UI should be fine.

**Comment by melezhik** [comment]
pleas check the last commit it should make what you want ...

**Comment by cfa** [comment]
The `--bootstrap` flag works well for me,

    $ tom --bootstrap
    Successfully installed Sparrow-0.2.53
    1 distribution installed
    $ tom
    [scenarios list]
    foo
    $ tom --bootstrap
    Sparrow is up to date. (0.3.10)
    $ tom
    [scenarios list]
    foo

though perhaps a system installation should be offered if `cpanm` isn't present? The current behaviour might not be ideal (`cpanm` removed to retest):

    $ tom --bootstrap
    /bin/sh: cpanm: command not found
    The spawned command 'cpanm --notest -q Sparrow' exited unsuccessfully (exit code: 127)
      in block <unit> at /Users/cfa/.rakudup/2018.12/install/share/perl6/site/resources/[...] line 6
      in sub MAIN at /Users/cfa/.rakudup/install/share/perl6/site/bin/tom line 2
      in block <unit> at /Users/cfa/.rakudup/install/share/perl6/site/bin/tom line 2

Suggestion: pull the system installation logic out of `scenario-run` and offer it as a fallback here too if the spawn fails (along with your note about requiring sudo)?

**Comment by melezhik** [comment]
Imho "cpanm: command not found" is quite clear to explain the failure reason.  Indeed if we consider different reasons of local bootstrap failure it could be many of them - lacking gcc or make as an example. It's really hard to pragmatically catch all the cases in local bootstrap, this is why people might want system bootstrap where all the none Perl dependencies are being installed.

**Comment by cfa** [comment]
True, though you offer system installation on the first attempted scenario run, right? I'm not sure why there's a discrepancy between the initial `--bootstrap` and this attempt to satisfy dependencies at runtime.

**Comment by melezhik** [comment]
Probably you tested against old commit. Nit sure. Right now yes during every scenario run if sparrow is not present they are given a choice of local/system install.
Explicit tom --bootstrap command runs local install.

**Comment by cfa** [comment]
I only tested with one scenario run; understood.

Thanks.
