### ISSUE TITLE
zef cannot find tomtit

### ISSUE THREAD

**Issue by ngaywood** [melezhik/Tomtit#1]

**Comment by ngaywood** [comment]
$ zef install tomtit
===> Searching for: tomtit
No candidates found matching identity: tomtit

$ raku --version
Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2021.08.
Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
Built on MoarVM version 2021.08.

**Comment by melezhik** [comment]
Hi! I guess it should be:

   zef install Tomtit

**Comment by melezhik** [comment]
And then, after installation:

     export SP6_REPO=http://sparrowhub.io/repo

To add sparrow repository

**Comment by melezhik** [comment]
Let me know if you need any help ...

**Comment by ngaywood** [comment]
Thanks for help. I'm suprised that "zef search tomtit" did not find "Tomtit". But that's a zef issue.

Could I suggest an update to your README.md file, from:
  zef install tomtit
to:
  zef install Tomtit

**Comment by melezhik** [comment]
@ngaywood  thank you for pointing this out, fixed.
