### ISSUE TITLE
Task dependencies support?

### ISSUE THREAD

**Issue by melezhik** [melezhik/tomtit#4]
Based on - https://gitlab.com/jjatria/publicsuffix/-/merge_requests/1#note_1064614348

> Thanks for all the work you've put into this!
>  I do worry a little about the duplication, but maybe that's not such a bad problem. Are there no plans to give tom the ability to | have tasks depend on each other, like make or ake does? It would make writing things like this easier.
>  I'll have to think about this when I get some time. It'd be nice to solve this using a Raku tool.

by @jjatria

**Comment by melezhik** [comment]
By design I did not have any task dependencies mechanism ( at least in a declarative way ) in tomtit. 
Advantages I see here:  to make high level tomtit scenarios code as simple as possible to avoid any complexity ... 

Thus, any tomtit scenario would have _all the dependencies explicitly_ as a tasks list:

```raku
task-run ("path/task1");
task-run ("path/task2");
task-run ("path/task3");
task-run ("path/task4");
```

In that sense any code reuse happens of task level, where _the same task_ might be called from within many scenarios: 

`tom./scenario1.raku`:

```raku
task-run ("path/task1");
```

`tom./scenario2.raku`:

```raku
task-run ("path/task1");
```

However, I do understand that consequences  of such approach could be some "code duplication" in a sense we reuse code on per task not per scenario level and we do so in imperative not declarative way.

However somewhat desired declarative style functionality could be achieved by using `EVALFILE`:

`tom./scenario1.raku`: 

```
task-run ("path/task1");
EVALFILE("tom./scenario2.raku");
```

Just a a thought, what do you think?

**Comment by melezhik** [comment]
@jjatria you may consider Cromtit where job dependencies for Tomtit projects are supported

**Comment by melezhik** [comment]
https://github.com/melezhik/Cromtit#job-dependencies

**Comment by jjatria** [comment]
Thanks for all the work you've put into this! I will really try to take a look at this as soon as I can. I've just got a lot on my plate at the moment...

**Comment by melezhik** [comment]
@jjatria no rush at all, just throwing some possible ideas …

**Comment by melezhik** [comment]
closing this now, @jjatria please feel free to reopen if you are still interested.
